#!/usr/bin/env python3
"""Train configurable GNNs on chemotactic cell-migration trajectories.

This trainer follows the overall conventions of ``../1D_traffic/scripts/train.py``:
trajectory-disjoint train/validation/test splits, normalization learned only
from the training split, JSON configuration with command-line overrides,
early stopping, and a self-contained checkpoint.

The model input deliberately does *not* use a precomputed, state-dependent
advection operator. At every rollout step the core node features are density,
chemoattractant, cell area, and a boundary flag. The prescribed drift velocity
chi*grad(c), chemotactic sensitivity chi, absolute center coordinates, and four
distances to the rectangular domain boundaries are independently configurable.

All continuous channels are normalized with training-split statistics. The
static chemical field and mesh features (and chi, when included) stay fixed
within a trajectory; only density is replaced autoregressively. Stored mesh
edge attributes provide geometry to MeshGraphNet and FluxGraphNet. SAGEConv
uses graph connectivity and the node-level geometry.

``autoregressive_steps=1`` gives ordinary one-step training.  Values greater
than one unroll the model without teacher forcing: each predicted density is
fed to the next step and gradients propagate through the complete unroll.

Supported targets are:

* ``state``: predict n(t + dt)
* ``delta``: predict n(t + dt) - n(t)
* ``rate``:  predict (n(t + dt) - n(t)) / dt

For FluxGraphNet, ``node_weight_loss`` and ``flux_loss_weight`` control a
weighted sum of node-state rollout MSE and direct interface-transport MSE.
Flux targets must be present in archives generated by the current data
generator; setting ``flux_loss_weight=0`` preserves node-only training. Both
weight settings are ignored by SAGEConv and MeshGraphNet, which use the
standard unweighted node objective.

By default, FluxGraphNet's face decoder emits transport in physical units.
Setting ``decode_normalized_flux=true`` instead makes it emit a dimensionless
standardized value and applies ``flux_mean + flux_std * decoded_flux`` before
the conservative finite-volume update. The flux statistics are learned from
training trajectories only and are stored in the checkpoint.

FluxGraphNet decodes one signed transport per interior face and applies equal
and opposite mass changes to the adjacent finite-volume cells.  It therefore
conserves area-weighted mass by construction, including for ``state`` targets.

Example:

    python scripts/train.py --config config_chemotaxis_gnn.json

Explicit command-line values override the JSON config:

    python scripts/train.py --config config_chemotaxis_gnn.json \
        --model meshgraphnet --target-type rate --autoregressive-steps 8
"""

from __future__ import annotations

import argparse
import copy
import json
import random
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    import torch
    import torch.nn.functional as F
    from torch import Tensor, nn
    from torch.optim import AdamW
    from torch_geometric.data import Data
    from torch_geometric.loader import DataLoader
    from torch_geometric.nn import SAGEConv
except ModuleNotFoundError as exc:
    raise SystemExit(
        "This script requires PyTorch and PyTorch Geometric. Install them "
        "for your platform and rerun the command."
    ) from exc


TARGET_TYPES = ("state", "delta", "rate")
MODEL_NAMES = ("sageconv", "meshgraphnet", "fluxgraphnet")


@dataclass(frozen=True)
class Normalization:
    """Training-split normalization statistics."""

    density_mean: float
    density_std: float
    target_mean: float
    target_std: float
    static_continuous_mean: List[float]
    static_continuous_std: List[float]
    edge_mean: List[float]
    edge_std: List[float]


@dataclass(frozen=True)
class FluxNormalization:
    """Scalar statistics fitted on training interface-flux targets."""

    mean: float
    std: float


def _safe_std(value: np.ndarray, *, minimum: float = 1.0e-8) -> np.ndarray:
    """Replace effectively constant standard deviations by one."""
    value = np.asarray(value, dtype=np.float64)
    return np.where(value > minimum, value, 1.0)


def _scalar(array: np.ndarray, name: str) -> float:
    value = np.asarray(array)
    if value.ndim != 0:
        raise ValueError(f"{name} must be a scalar; got shape {value.shape}.")
    return float(value.item())


def load_archive(path: Path) -> Dict[str, np.ndarray]:
    """Load and validate the trajectory-specific chemotaxis graph archive."""
    if not path.is_file():
        raise FileNotFoundError(f"Dataset does not exist: {path}")
    with np.load(path, allow_pickle=False) as archive:
        data = {name: archive[name] for name in archive.files}

    required = (
        "rollout_states",
        "chemoattractant",
        "chi",
        "dt",
        "pos",
        "cell_areas",
        "boundary_cell_mask",
        "edge_index",
        "edge_attr",
        "undirected_edge_index",
    )
    missing = [name for name in required if name not in data]
    if missing:
        raise KeyError("Dataset is missing required arrays: " + ", ".join(missing))

    states = np.asarray(data["rollout_states"])
    if states.ndim != 4 or states.shape[-1] != 1:
        raise ValueError(
            "rollout_states must have shape [trajectory, time, node, 1]."
        )
    num_trajectories, num_frames, num_nodes, _ = states.shape
    if num_frames < 2:
        raise ValueError("rollout_states must contain at least two frames.")

    expected_node_shapes = {
        "chemoattractant": (num_trajectories, num_nodes, 1),
        "pos": (num_trajectories, num_nodes, 2),
        "cell_areas": (num_trajectories, num_nodes),
        "boundary_cell_mask": (num_trajectories, num_nodes),
    }
    for name, expected in expected_node_shapes.items():
        if np.asarray(data[name]).shape != expected:
            raise ValueError(
                f"{name} has shape {np.asarray(data[name]).shape}; "
                f"expected {expected}."
            )

    edge_index = np.asarray(data["edge_index"])
    edge_attr = np.asarray(data["edge_attr"])
    undirected = np.asarray(data["undirected_edge_index"])
    if edge_index.ndim != 3 or edge_index.shape[0:2] != (num_trajectories, 2):
        raise ValueError("edge_index must have shape [trajectory, 2, edge].")
    if edge_attr.ndim != 3 or edge_attr.shape[:2] != (
        num_trajectories,
        edge_index.shape[2],
    ):
        raise ValueError(
            "edge_attr must have shape [trajectory, edge, channel] and align "
            "with edge_index."
        )
    if undirected.ndim != 3 or undirected.shape[0:2] != (num_trajectories, 2):
        raise ValueError(
            "undirected_edge_index must have shape [trajectory, 2, face]."
        )
    num_faces = undirected.shape[2]
    if edge_index.shape[2] != 2 * num_faces:
        raise ValueError(
            "Expected exactly two directed graph edges per interior face."
        )
    if not np.array_equal(edge_index[:, :, :num_faces], undirected):
        raise ValueError(
            "The first half of edge_index must match undirected_edge_index."
        )
    if not np.array_equal(
        edge_index[:, :, num_faces:], undirected[:, ::-1, :]
    ):
        raise ValueError(
            "The second half of edge_index must contain reversed interior edges."
        )
    if np.any(np.asarray(data["cell_areas"]) <= 0.0):
        raise ValueError("Every cell area must be positive.")
    if not np.all(np.isfinite(states)):
        raise ValueError("rollout_states contains non-finite values.")
    if _scalar(data["dt"], "dt") <= 0.0:
        raise ValueError("dt must be positive.")

    chi = np.asarray(data["chi"], dtype=np.float64)
    if chi.ndim == 0:
        chi = np.full(num_trajectories, float(chi), dtype=np.float64)
    if chi.shape != (num_trajectories,):
        raise ValueError(
            f"chi must be scalar or shape [{num_trajectories}]; got {chi.shape}."
        )
    if np.any(chi < 0.0) or not np.all(np.isfinite(chi)):
        raise ValueError("chi values must be finite and nonnegative.")
    data["trajectory_chi"] = chi
    return data


def split_trajectories(
    num_trajectories: int,
    *,
    train_fraction: float,
    validation_fraction: float,
    test_fraction: float,
    seed: int,
) -> Dict[str, np.ndarray]:
    """Create deterministic, mutually exclusive trajectory splits."""
    fractions = np.asarray(
        [train_fraction, validation_fraction, test_fraction], dtype=np.float64
    )
    if np.any(fractions <= 0.0) or not np.isclose(fractions.sum(), 1.0):
        raise ValueError(
            "train_fraction, validation_fraction, and test_fraction must be "
            "positive and sum to one."
        )
    if num_trajectories < 3:
        raise ValueError("At least three trajectories are required for three splits.")

    order = np.random.default_rng(seed).permutation(num_trajectories)
    train_count = max(1, int(np.floor(train_fraction * num_trajectories)))
    validation_count = max(
        1, int(np.floor(validation_fraction * num_trajectories))
    )
    if train_count + validation_count >= num_trajectories:
        validation_count = 1
        train_count = num_trajectories - 2
    test_count = num_trajectories - train_count - validation_count
    if min(train_count, validation_count, test_count) <= 0:
        raise ValueError("The requested fractions produced an empty split.")
    return {
        "train": np.sort(order[:train_count]),
        "validation": np.sort(
            order[train_count : train_count + validation_count]
        ),
        "test": np.sort(order[train_count + validation_count :]),
    }


def static_continuous_feature_names(
    *,
    include_chi: bool = True,
    include_drift_velocity: bool = False,
    include_absolute_positions: bool = True,
    include_boundary_distances: bool = False,
) -> List[str]:
    """Return ordered names for the configurable continuous node channels."""
    names = ["chemoattractant"]
    if include_chi:
        names.append("chi")
    if include_drift_velocity:
        names.extend(("drift_velocity_x", "drift_velocity_y"))
    if include_absolute_positions:
        names.extend(("pos_x", "pos_y"))
    names.append("cell_area")
    if include_boundary_distances:
        names.extend(
            (
                "distance_to_left_boundary",
                "distance_to_right_boundary",
                "distance_to_bottom_boundary",
                "distance_to_top_boundary",
            )
        )
    return names


def raw_static_continuous_features(
    data: Dict[str, np.ndarray],
    *,
    include_chi: bool = True,
    include_drift_velocity: bool = False,
    include_absolute_positions: bool = True,
    include_boundary_distances: bool = False,
) -> np.ndarray:
    """Construct configurable node inputs without physics-precomputed fields."""
    chemo = np.asarray(data["chemoattractant"], dtype=np.float64)
    pos = np.asarray(data["pos"], dtype=np.float64)
    area = np.asarray(data["cell_areas"], dtype=np.float64)[..., None]
    components = [chemo]
    if include_chi:
        num_nodes = chemo.shape[1]
        chi = np.broadcast_to(
            np.asarray(data["trajectory_chi"], dtype=np.float64)[:, None, None],
            (chemo.shape[0], num_nodes, 1),
        )
        components.append(chi)
    if include_drift_velocity:
        if "drift_velocity" not in data:
            raise KeyError(
                "Drift-velocity inputs require drift_velocity in the dataset."
            )
        drift_velocity = np.asarray(data["drift_velocity"], dtype=np.float64)
        expected_shape = (chemo.shape[0], chemo.shape[1], 2)
        if drift_velocity.shape != expected_shape:
            raise ValueError(
                f"drift_velocity has shape {drift_velocity.shape}; "
                f"expected {expected_shape}."
            )
        if not np.all(np.isfinite(drift_velocity)):
            raise ValueError("drift_velocity contains non-finite values.")
        components.append(drift_velocity)
    if include_absolute_positions:
        components.append(pos)
    components.append(area)
    if include_boundary_distances:
        if "lx" not in data or "ly" not in data:
            raise KeyError(
                "Boundary-distance inputs require scalar lx and ly in the dataset."
            )
        lx = _scalar(data["lx"], "lx")
        ly = _scalar(data["ly"], "ly")
        if lx <= 0.0 or ly <= 0.0:
            raise ValueError("lx and ly must be positive.")
        boundary_distances = np.stack(
            (
                pos[..., 0],
                lx - pos[..., 0],
                pos[..., 1],
                ly - pos[..., 1],
            ),
            axis=-1,
        )
        if np.any(boundary_distances < -1.0e-10):
            raise ValueError("A node center lies outside the rectangular domain.")
        components.append(np.maximum(boundary_distances, 0.0))
    return np.concatenate(components, axis=-1)


def target_array(states: np.ndarray, target_type: str, dt: float) -> np.ndarray:
    """Construct ground-truth one-step targets from full trajectories."""
    if target_type == "state":
        return states[:, 1:]
    delta = states[:, 1:] - states[:, :-1]
    if target_type == "delta":
        return delta
    if target_type == "rate":
        return delta / dt
    raise ValueError(f"Unknown target_type {target_type!r}.")


def interface_flux_targets(
    data: Dict[str, np.ndarray], target_type: str
) -> np.ndarray:
    """Return decoder-aligned face targets in delta/state or rate units."""
    if "interface_flux_transport" not in data:
        raise KeyError(
            "Flux supervision requires interface_flux_transport in the dataset. "
            "Regenerate it with the current data generator."
        )
    transport = np.asarray(data["interface_flux_transport"], dtype=np.float64)
    states = np.asarray(data["rollout_states"])
    num_trajectories = states.shape[0]
    num_steps = states.shape[1] - 1
    num_faces = np.asarray(data["undirected_edge_index"]).shape[2]
    expected = (num_trajectories, num_steps, num_faces, 1)
    if transport.shape != expected:
        raise ValueError(
            f"interface_flux_transport has shape {transport.shape}; expected {expected}."
        )
    if not np.all(np.isfinite(transport)):
        raise ValueError("interface_flux_transport contains non-finite values.")
    if target_type == "rate":
        transport = transport / _scalar(data["dt"], "dt")
    elif target_type not in ("state", "delta"):
        raise ValueError(f"Unknown target_type {target_type!r}.")
    return transport.astype(np.float32)


def compute_flux_normalization(
    flux_targets: np.ndarray, train_ids: np.ndarray
) -> FluxNormalization:
    """Fit scalar face-target normalization on training trajectories only."""
    train_flux = np.asarray(flux_targets, dtype=np.float64)[train_ids]
    mean = float(np.mean(train_flux, dtype=np.float64))
    std = float(np.std(train_flux, dtype=np.float64))
    return FluxNormalization(mean=mean, std=max(std, 1.0e-10))


def compute_normalization(
    data: Dict[str, np.ndarray],
    train_ids: np.ndarray,
    *,
    target_type: str,
    include_chi: bool = True,
    include_drift_velocity: bool = False,
    include_absolute_positions: bool = True,
    include_boundary_distances: bool = False,
) -> Normalization:
    """Compute all scalar/channel statistics from training trajectories only."""
    states = np.asarray(data["rollout_states"], dtype=np.float64)[train_ids]
    density_mean = float(states.mean(dtype=np.float64))
    density_std = max(float(states.std(dtype=np.float64)), 1.0e-8)
    target = target_array(states, target_type, _scalar(data["dt"], "dt"))
    target_mean = float(target.mean(dtype=np.float64))
    target_std = max(float(target.std(dtype=np.float64)), 1.0e-10)

    static = raw_static_continuous_features(
        data,
        include_chi=include_chi,
        include_drift_velocity=include_drift_velocity,
        include_absolute_positions=include_absolute_positions,
        include_boundary_distances=include_boundary_distances,
    )[train_ids]
    static_mean = static.mean(axis=(0, 1), dtype=np.float64)
    static_std = _safe_std(static.std(axis=(0, 1), dtype=np.float64))
    edges = np.asarray(data["edge_attr"], dtype=np.float64)[train_ids]
    edge_mean = edges.mean(axis=(0, 1), dtype=np.float64)
    edge_std = _safe_std(edges.std(axis=(0, 1), dtype=np.float64))
    return Normalization(
        density_mean=density_mean,
        density_std=density_std,
        target_mean=target_mean,
        target_std=target_std,
        static_continuous_mean=static_mean.tolist(),
        static_continuous_std=static_std.tolist(),
        edge_mean=edge_mean.tolist(),
        edge_std=edge_std.tolist(),
    )


def prepare_features(
    data: Dict[str, np.ndarray],
    normalization: Normalization,
    *,
    include_chi: bool = True,
    include_drift_velocity: bool = False,
    include_absolute_positions: bool = True,
    include_boundary_distances: bool = False,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Normalize static node and directed/undirected edge features."""
    continuous = raw_static_continuous_features(
        data,
        include_chi=include_chi,
        include_drift_velocity=include_drift_velocity,
        include_absolute_positions=include_absolute_positions,
        include_boundary_distances=include_boundary_distances,
    )
    continuous_mean = np.asarray(
        normalization.static_continuous_mean, dtype=np.float64
    )
    continuous_std = np.asarray(
        normalization.static_continuous_std, dtype=np.float64
    )
    normalized_continuous = (continuous - continuous_mean) / continuous_std
    boundary = np.asarray(data["boundary_cell_mask"], dtype=np.float64)[..., None]
    static_node_features = np.concatenate(
        (normalized_continuous, boundary), axis=-1
    ).astype(np.float32)

    edge_mean = np.asarray(normalization.edge_mean, dtype=np.float64)
    edge_std = np.asarray(normalization.edge_std, dtype=np.float64)
    edge_attr = (
        (np.asarray(data["edge_attr"], dtype=np.float64) - edge_mean) / edge_std
    ).astype(np.float32)
    num_faces = np.asarray(data["undirected_edge_index"]).shape[2]
    undirected_edge_attr = edge_attr[:, :num_faces].copy()
    return static_node_features, edge_attr, undirected_edge_attr


class ChemotaxisRolloutDataset(torch.utils.data.Dataset):
    """Lazy dataset of trajectory windows on trajectory-specific graphs."""

    def __init__(
        self,
        *,
        data: Dict[str, np.ndarray],
        trajectory_ids: np.ndarray,
        autoregressive_steps: int,
        static_node_features: np.ndarray,
        edge_attr: np.ndarray,
        undirected_edge_attr: np.ndarray,
        flux_targets: Optional[np.ndarray] = None,
    ) -> None:
        self.states = np.asarray(data["rollout_states"], dtype=np.float32)
        self.edge_index = np.asarray(data["edge_index"], dtype=np.int64)
        self.undirected_edge_index = np.asarray(
            data["undirected_edge_index"], dtype=np.int64
        )
        self.cell_areas = np.asarray(data["cell_areas"], dtype=np.float32)
        self.static_node_features = static_node_features
        self.edge_attr = edge_attr
        self.undirected_edge_attr = undirected_edge_attr
        self.flux_targets = flux_targets
        self.trajectory_ids = np.asarray(trajectory_ids, dtype=np.int64)
        self.autoregressive_steps = int(autoregressive_steps)
        self.dt = _scalar(data["dt"], "dt")
        self.num_nodes = int(self.states.shape[2])
        self.starts_per_trajectory = (
            self.states.shape[1] - self.autoregressive_steps
        )
        if self.autoregressive_steps <= 0:
            raise ValueError("autoregressive_steps must be positive.")
        if self.starts_per_trajectory <= 0:
            raise ValueError(
                "autoregressive_steps cannot exceed the number of stored transitions."
            )

    def __len__(self) -> int:
        return int(self.trajectory_ids.size * self.starts_per_trajectory)

    def __getitem__(self, item: int) -> Data:
        if item < 0:
            item += len(self)
        if item < 0 or item >= len(self):
            raise IndexError(item)
        split_trajectory = item // self.starts_per_trajectory
        start = item % self.starts_per_trajectory
        trajectory = int(self.trajectory_ids[split_trajectory])
        stop = start + self.autoregressive_steps + 1
        # Node-major layout lets PyG concatenate rollout windows by node.
        rollout = np.transpose(self.states[trajectory, start:stop], (1, 0, 2))
        area = self.cell_areas[trajectory, :, None]
        attributes = dict(
            static_node_features=torch.from_numpy(
                self.static_node_features[trajectory]
            ),
            rollout=torch.from_numpy(np.ascontiguousarray(rollout)),
            edge_index=torch.from_numpy(self.edge_index[trajectory]).long(),
            edge_attr=torch.from_numpy(self.edge_attr[trajectory]),
            undirected_edge_index=torch.from_numpy(
                self.undirected_edge_index[trajectory]
            ).long(),
            undirected_edge_attr=torch.from_numpy(
                self.undirected_edge_attr[trajectory]
            ),
            cell_area=torch.from_numpy(area),
            dt_node=torch.full(
                (self.num_nodes, 1), self.dt, dtype=torch.float32
            ),
            trajectory_id=torch.tensor([trajectory], dtype=torch.long),
            time_index=torch.tensor([start], dtype=torch.long),
            num_nodes=self.num_nodes,
        )
        if self.flux_targets is not None:
            flux_stop = start + self.autoregressive_steps
            # Face-major layout lets PyG concatenate per-graph face sequences.
            flux_target = np.transpose(
                self.flux_targets[trajectory, start:flux_stop], (1, 0, 2)
            )
            attributes["flux_target"] = torch.from_numpy(
                np.ascontiguousarray(flux_target)
            )
        return Data(**attributes)


class SAGENet(nn.Module):
    """Residual GraphSAGE stack with a scalar normalized-target output."""

    def __init__(
        self,
        *,
        in_channels: int,
        hidden_channels: int,
        num_layers: int,
        dropout: float,
        layer_norm: bool = False,
    ) -> None:
        super().__init__()
        if num_layers < 2:
            raise ValueError("SAGEConv requires num_layers >= 2.")
        dimensions = [in_channels] + [hidden_channels] * num_layers
        self.convolutions = nn.ModuleList(
            SAGEConv(dimensions[index], dimensions[index + 1])
            for index in range(num_layers)
        )
        self.normalizations = nn.ModuleList(
            nn.LayerNorm(hidden_channels) if layer_norm else nn.Identity()
            for _ in range(num_layers)
        )
        self.output = nn.Linear(hidden_channels, 1)
        self.dropout = float(dropout)

    def forward(self, x: Tensor, edge_index: Tensor, **_: Tensor) -> Tensor:
        hidden = x
        for index, (convolution, normalization) in enumerate(
            zip(self.convolutions, self.normalizations)
        ):
            updated = convolution(hidden, edge_index)
            updated = normalization(updated)
            updated = F.silu(updated)
            updated = F.dropout(updated, p=self.dropout, training=self.training)
            if index > 0:
                updated = updated + hidden
            hidden = updated
        return self.output(hidden)


def _make_mlp(
    *,
    in_channels: int,
    hidden_channels: int,
    out_channels: int,
    dropout: float,
    layer_norm: bool,
) -> nn.Sequential:
    layers: List[nn.Module] = [
        nn.Linear(in_channels, hidden_channels),
        nn.SiLU(),
        nn.Dropout(dropout),
        nn.Linear(hidden_channels, out_channels),
    ]
    if layer_norm:
        layers.append(nn.LayerNorm(out_channels))
    return nn.Sequential(*layers)


class MeshGraphNetBlock(nn.Module):
    """Residual edge-update/node-update graph-network block."""

    def __init__(
        self, *, hidden_channels: int, dropout: float, layer_norm: bool
    ) -> None:
        super().__init__()
        self.edge_mlp = _make_mlp(
            in_channels=3 * hidden_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.node_mlp = _make_mlp(
            in_channels=2 * hidden_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )

    def forward(
        self, node_features: Tensor, edge_features: Tensor, edge_index: Tensor
    ) -> Tuple[Tensor, Tensor]:
        senders, receivers = edge_index
        edge_update = self.edge_mlp(
            torch.cat(
                (
                    node_features[senders],
                    node_features[receivers],
                    edge_features,
                ),
                dim=-1,
            )
        )
        updated_edges = edge_features + edge_update
        aggregated = torch.zeros_like(node_features)
        aggregated.index_add_(0, receivers, updated_edges)
        node_update = self.node_mlp(
            torch.cat((node_features, aggregated), dim=-1)
        )
        return node_features + node_update, updated_edges


class MeshGraphNet(nn.Module):
    """Encode-process-decode MeshGraphNet using stored mesh geometry."""

    def __init__(
        self,
        *,
        in_channels: int,
        edge_attr_channels: int,
        hidden_channels: int,
        num_layers: int,
        dropout: float,
        layer_norm: bool = False,
    ) -> None:
        super().__init__()
        if num_layers < 1:
            raise ValueError("MeshGraphNet requires num_layers >= 1.")
        self.node_encoder = _make_mlp(
            in_channels=in_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.edge_encoder = _make_mlp(
            in_channels=edge_attr_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.processor = nn.ModuleList(
            MeshGraphNetBlock(
                hidden_channels=hidden_channels,
                dropout=dropout,
                layer_norm=layer_norm,
            )
            for _ in range(num_layers)
        )
        self.decoder = _make_mlp(
            in_channels=hidden_channels,
            hidden_channels=hidden_channels,
            out_channels=1,
            dropout=dropout,
            layer_norm=False,
        )

    def forward(
        self, x: Tensor, edge_index: Tensor, *, edge_attr: Tensor, **_: Tensor
    ) -> Tensor:
        node_features = self.node_encoder(x)
        edge_features = self.edge_encoder(edge_attr)
        for block in self.processor:
            node_features, edge_features = block(
                node_features, edge_features, edge_index
            )
        return self.decoder(node_features)


class FluxGraphNet(nn.Module):
    """Mesh graph network with an exactly conservative interior-face decoder."""

    def __init__(
        self,
        *,
        in_channels: int,
        edge_attr_channels: int,
        hidden_channels: int,
        num_layers: int,
        dropout: float,
        layer_norm: bool,
        target_type: str,
        target_mean: float,
        target_std: float,
        decode_normalized_flux: bool = False,
        flux_mean: float = 0.0,
        flux_std: float = 1.0,
    ) -> None:
        super().__init__()
        if num_layers < 1:
            raise ValueError("FluxGraphNet requires num_layers >= 1.")
        if target_type not in TARGET_TYPES:
            raise ValueError(f"Unsupported target_type {target_type!r}.")
        if not isinstance(decode_normalized_flux, bool):
            raise ValueError("decode_normalized_flux must be boolean.")
        if not np.isfinite(flux_mean):
            raise ValueError("flux_mean must be finite.")
        if not np.isfinite(flux_std) or flux_std <= 0.0:
            raise ValueError("flux_std must be finite and positive.")
        self.target_type = target_type
        self.decode_normalized_flux = decode_normalized_flux
        self.register_buffer(
            "target_mean", torch.tensor(float(target_mean), dtype=torch.float32)
        )
        self.register_buffer(
            "target_std", torch.tensor(float(target_std), dtype=torch.float32)
        )
        # These buffers are reconstructed from model_kwargs and deliberately
        # omitted from state_dict so checkpoints created before this option
        # remain loadable without missing-buffer errors.
        self.register_buffer(
            "flux_mean",
            torch.tensor(float(flux_mean), dtype=torch.float32),
            persistent=False,
        )
        self.register_buffer(
            "flux_std",
            torch.tensor(float(flux_std), dtype=torch.float32),
            persistent=False,
        )
        self.node_encoder = _make_mlp(
            in_channels=in_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.edge_encoder = _make_mlp(
            in_channels=edge_attr_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.processor = nn.ModuleList(
            MeshGraphNetBlock(
                hidden_channels=hidden_channels,
                dropout=dropout,
                layer_norm=layer_norm,
            )
            for _ in range(num_layers)
        )
        self.face_encoder = _make_mlp(
            in_channels=edge_attr_channels,
            hidden_channels=hidden_channels,
            out_channels=hidden_channels,
            dropout=dropout,
            layer_norm=layer_norm,
        )
        self.flux_decoder = _make_mlp(
            in_channels=3 * hidden_channels,
            hidden_channels=hidden_channels,
            out_channels=1,
            dropout=dropout,
            layer_norm=False,
        )
        final_layer = self.flux_decoder[-1]
        if not isinstance(final_layer, nn.Linear):
            raise RuntimeError("Flux decoder must end in a linear layer.")
        nn.init.zeros_(final_layer.weight)
        nn.init.zeros_(final_layer.bias)

    def predict_target_and_flux(
        self,
        x: Tensor,
        edge_index: Tensor,
        *,
        edge_attr: Tensor,
        undirected_edge_index: Tensor,
        undirected_edge_attr: Tensor,
        cell_area: Tensor,
        current: Tensor,
        **_: Tensor,
    ) -> Tuple[Tensor, Tensor]:
        """Return the normalized node target and oriented face transport."""
        if cell_area.ndim == 1:
            cell_area = cell_area.unsqueeze(-1)
        if cell_area.shape != (x.shape[0], 1):
            raise ValueError("cell_area must have shape [node, 1].")
        if bool(torch.any(cell_area <= 0.0)):
            raise ValueError("cell_area values must be positive.")

        node_features = self.node_encoder(x)
        edge_features = self.edge_encoder(edge_attr)
        for block in self.processor:
            node_features, edge_features = block(
                node_features, edge_features, edge_index
            )

        face_features = self.face_encoder(undirected_edge_attr)
        sources, receivers = undirected_edge_index
        decoded_face_transport = self.flux_decoder(
            torch.cat(
                (
                    node_features[sources],
                    node_features[receivers],
                    face_features,
                ),
                dim=-1,
            )
        )
        face_transport = (
            self.flux_mean + self.flux_std * decoded_face_transport
            if self.decode_normalized_flux
            else decoded_face_transport
        )
        mass_change = torch.zeros(
            (x.shape[0], 1), dtype=x.dtype, device=x.device
        )
        mass_change.index_add_(0, sources, -face_transport)
        mass_change.index_add_(0, receivers, face_transport)
        update = mass_change / cell_area
        raw_target = current + update if self.target_type == "state" else update
        normalized_target = (raw_target - self.target_mean) / self.target_std
        return normalized_target, face_transport

    def forward(
        self,
        x: Tensor,
        edge_index: Tensor,
        *,
        edge_attr: Tensor,
        undirected_edge_index: Tensor,
        undirected_edge_attr: Tensor,
        cell_area: Tensor,
        current: Tensor,
        **kwargs: Tensor,
    ) -> Tensor:
        normalized_target, _ = self.predict_target_and_flux(
            x,
            edge_index,
            edge_attr=edge_attr,
            undirected_edge_index=undirected_edge_index,
            undirected_edge_attr=undirected_edge_attr,
            cell_area=cell_area,
            current=current,
            **kwargs,
        )
        return normalized_target


MODEL_CLASSES = {
    "sageconv": SAGENet,
    "meshgraphnet": MeshGraphNet,
    "fluxgraphnet": FluxGraphNet,
}


def build_model(
    model_name: str,
    *,
    in_channels: int,
    edge_attr_channels: int,
    hidden_channels: int,
    num_layers: int,
    dropout: float,
    layer_norm: bool,
    target_type: str,
    normalization: Normalization,
    decode_normalized_flux: bool = False,
    flux_normalization: Optional[FluxNormalization] = None,
) -> Tuple[nn.Module, Dict[str, object]]:
    """Construct one of the three configured architectures."""
    common: Dict[str, object] = {
        "in_channels": int(in_channels),
        "hidden_channels": int(hidden_channels),
        "num_layers": int(num_layers),
        "dropout": float(dropout),
        "layer_norm": bool(layer_norm),
    }
    if model_name == "sageconv":
        kwargs = dict(common)
    elif model_name == "meshgraphnet":
        kwargs = dict(common, edge_attr_channels=int(edge_attr_channels))
    elif model_name == "fluxgraphnet":
        if decode_normalized_flux and flux_normalization is None:
            raise ValueError(
                "Normalized-flux decoding requires training-split flux "
                "normalization statistics."
            )
        kwargs = dict(
            common,
            edge_attr_channels=int(edge_attr_channels),
            target_type=target_type,
            target_mean=normalization.target_mean,
            target_std=normalization.target_std,
            decode_normalized_flux=bool(decode_normalized_flux),
            flux_mean=(
                flux_normalization.mean if flux_normalization is not None else 0.0
            ),
            flux_std=(
                flux_normalization.std if flux_normalization is not None else 1.0
            ),
        )
    else:
        raise ValueError(
            f"Unknown model {model_name!r}; expected one of {MODEL_NAMES}."
        )
    return MODEL_CLASSES[model_name](**kwargs), kwargs


def model_from_checkpoint(checkpoint: Dict[str, object]) -> nn.Module:
    """Reconstruct any supported architecture from a trusted checkpoint."""
    model_name = checkpoint.get("model_name")
    if model_name is None:
        class_to_name = {
            model_class.__name__: name
            for name, model_class in MODEL_CLASSES.items()
        }
        model_name = class_to_name.get(str(checkpoint.get("model_class", "")))
    if model_name not in MODEL_CLASSES:
        raise ValueError(
            f"Checkpoint model is not one of the supported architectures: "
            f"{MODEL_NAMES}."
        )
    model_kwargs = checkpoint.get("model_kwargs")
    if not isinstance(model_kwargs, dict):
        raise ValueError("Checkpoint model_kwargs must be a dictionary.")
    return MODEL_CLASSES[str(model_name)](**dict(model_kwargs))


def decode_next_state(
    raw_target: Tensor, current: Tensor, target_type: str, dt: Tensor
) -> Tensor:
    if target_type == "state":
        return raw_target
    if target_type == "delta":
        return current + raw_target
    if target_type == "rate":
        return current + dt * raw_target
    raise ValueError(f"Unsupported target_type {target_type!r}.")


def project_conservative_target(
    raw_target: Tensor,
    *,
    current: Tensor,
    cell_area: Tensor,
    graph_index: Tensor,
    num_graphs: int,
    target_type: str,
) -> Tensor:
    """Project a state/delta/rate target onto per-graph mass conservation."""
    change = raw_target - current if target_type == "state" else raw_target
    weighted_change = cell_area * change
    mass_change = change.new_zeros((num_graphs, 1))
    mass_change.index_add_(0, graph_index, weighted_change)
    area_squared = change.new_zeros((num_graphs, 1))
    area_squared.index_add_(0, graph_index, cell_area.square())
    correction = (
        cell_area
        * mass_change[graph_index]
        / area_squared[graph_index].clamp_min(1.0e-12)
    )
    projected_change = change - correction
    return current + projected_change if target_type == "state" else projected_change


def predict_normalized_target(
    model: nn.Module, batch: Data, node_input: Tensor, current: Tensor
) -> Tensor:
    """Call any supported architecture through one interface."""
    return model(
        node_input,
        batch.edge_index,
        edge_attr=batch.edge_attr,
        undirected_edge_index=batch.undirected_edge_index,
        undirected_edge_attr=batch.undirected_edge_attr,
        cell_area=batch.cell_area,
        current=current,
    )


def predict_normalized_target_and_flux(
    model: nn.Module, batch: Data, node_input: Tensor, current: Tensor
) -> Tuple[Tensor, Tensor]:
    """Call FluxGraphNet while exposing its oriented face transport."""
    if not isinstance(model, FluxGraphNet):
        raise ValueError("Direct flux supervision requires FluxGraphNet.")
    return model.predict_target_and_flux(
        node_input,
        batch.edge_index,
        edge_attr=batch.edge_attr,
        undirected_edge_index=batch.undirected_edge_index,
        undirected_edge_attr=batch.undirected_edge_attr,
        cell_area=batch.cell_area,
        current=current,
    )


def autoregressive_batch(
    model: nn.Module,
    batch: Data,
    *,
    normalization: Normalization,
    target_type: str,
    autoregressive_steps: int,
    mass_projection: bool,
    node_weight_loss: float,
    flux_loss_weight: float,
    flux_normalization: Optional[FluxNormalization],
) -> Tuple[Tensor, Dict[str, float]]:
    """Unroll a batch and return differentiable loss plus detached metrics."""
    if batch.rollout.shape[1] != autoregressive_steps + 1:
        raise ValueError("Batch rollout width does not match autoregressive_steps.")
    current = batch.rollout[:, 0]
    total_loss = current.new_zeros(())
    normalized_sse = 0.0
    flux_normalized_sse = 0.0
    next_sse = 0.0
    mass_absolute_error = 0.0
    value_count = 0
    graph_step_count = 0
    flux_value_count = 0
    if flux_loss_weight > 0.0:
        if not isinstance(model, FluxGraphNet):
            raise ValueError("Direct flux supervision requires FluxGraphNet.")
        if flux_normalization is None:
            raise ValueError("Flux supervision requires flux normalization.")
        if not hasattr(batch, "flux_target"):
            raise ValueError("Flux-supervised batch has no flux_target.")

    for step in range(autoregressive_steps):
        normalized_density = (
            current - normalization.density_mean
        ) / normalization.density_std
        node_input = torch.cat(
            (normalized_density, batch.static_node_features), dim=-1
        )
        predicted_flux = None
        if flux_loss_weight > 0.0:
            prediction, predicted_flux = predict_normalized_target_and_flux(
                model, batch, node_input, current
            )
        else:
            prediction = predict_normalized_target(
                model, batch, node_input, current
            )
        raw_target = (
            prediction * normalization.target_std + normalization.target_mean
        )
        if mass_projection and not isinstance(model, FluxGraphNet):
            raw_target = project_conservative_target(
                raw_target,
                current=current,
                cell_area=batch.cell_area,
                graph_index=batch.batch,
                num_graphs=int(batch.num_graphs),
                target_type=target_type,
            )
            prediction = (
                raw_target - normalization.target_mean
            ) / normalization.target_std

        predicted_next = decode_next_state(
            raw_target, current, target_type, batch.dt_node
        )
        true_next = batch.rollout[:, step + 1]
        normalized_state_error = (
            predicted_next - true_next
        ) / normalization.density_std
        # A state-space rollout loss gives state/delta/rate parameterizations
        # the same physical objective and trains accumulated multi-step error
        # directly. Target normalization still controls the decoder scale.
        node_loss = torch.mean(normalized_state_error.square())
        flux_loss = current.new_zeros(())
        if flux_loss_weight > 0.0:
            if predicted_flux is None or flux_normalization is None:
                raise RuntimeError("Flux prediction or normalization is unavailable.")
            target_flux = batch.flux_target[:, step]
            if predicted_flux.shape != target_flux.shape:
                raise ValueError(
                    "Predicted and target flux shapes differ: "
                    f"{predicted_flux.shape} versus {target_flux.shape}."
                )
            normalized_flux_error = (
                predicted_flux - target_flux
            ) / flux_normalization.std
            flux_loss = torch.mean(normalized_flux_error.square())
            flux_normalized_sse += float(
                torch.sum(normalized_flux_error.detach().square())
            )
            flux_value_count += target_flux.numel()
        step_loss = node_weight_loss * node_loss + flux_loss_weight * flux_loss
        total_loss = total_loss + step_loss / autoregressive_steps

        with torch.no_grad():
            normalized_sse += float(torch.sum(normalized_state_error.square()))
            next_sse += float(F.mse_loss(
                predicted_next, true_next, reduction="sum"
            ))
            value_count += true_next.numel()
            node_mass_error = (
                (predicted_next - true_next) * batch.cell_area
            ).view(-1)
            graph_mass_error = node_mass_error.new_zeros(int(batch.num_graphs))
            graph_mass_error.index_add_(0, batch.batch, node_mass_error)
            mass_absolute_error += float(torch.sum(torch.abs(graph_mass_error)))
            graph_step_count += int(batch.num_graphs)
        current = predicted_next

    node_normalized_mse = normalized_sse / max(value_count, 1)
    flux_normalized_mse = (
        flux_normalized_sse / flux_value_count if flux_value_count > 0 else 0.0
    )
    metrics = {
        "normalized_mse": node_normalized_mse,
        "flux_normalized_mse": flux_normalized_mse,
        "weighted_total_loss": (
            node_weight_loss * node_normalized_mse
            + flux_loss_weight * flux_normalized_mse
        ),
        "next_state_rmse": float(np.sqrt(next_sse / max(value_count, 1))),
        "mass_mae": mass_absolute_error / max(graph_step_count, 1),
    }
    return total_loss, metrics


def train_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    *,
    device: torch.device,
    normalization: Normalization,
    target_type: str,
    autoregressive_steps: int,
    mass_projection: bool,
    gradient_clip_norm: float,
    node_weight_loss: float,
    flux_loss_weight: float,
    flux_normalization: Optional[FluxNormalization],
) -> Dict[str, float]:
    model.train()
    weighted_metrics = {
        "normalized_mse": 0.0,
        "flux_normalized_mse": 0.0,
        "weighted_total_loss": 0.0,
        "next_state_rmse_squared": 0.0,
        "mass_mae": 0.0,
    }
    graph_steps = 0
    for batch in loader:
        batch = batch.to(device)
        optimizer.zero_grad(set_to_none=True)
        loss, metrics = autoregressive_batch(
            model,
            batch,
            normalization=normalization,
            target_type=target_type,
            autoregressive_steps=autoregressive_steps,
            mass_projection=mass_projection,
            node_weight_loss=node_weight_loss,
            flux_loss_weight=flux_loss_weight,
            flux_normalization=flux_normalization,
        )
        loss.backward()
        if gradient_clip_norm > 0.0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), gradient_clip_norm)
        optimizer.step()
        weight = int(batch.num_graphs) * autoregressive_steps
        graph_steps += weight
        weighted_metrics["normalized_mse"] += metrics["normalized_mse"] * weight
        weighted_metrics["flux_normalized_mse"] += (
            metrics["flux_normalized_mse"] * weight
        )
        weighted_metrics["weighted_total_loss"] += (
            metrics["weighted_total_loss"] * weight
        )
        weighted_metrics["next_state_rmse_squared"] += (
            metrics["next_state_rmse"] ** 2 * weight
        )
        weighted_metrics["mass_mae"] += metrics["mass_mae"] * weight
    divisor = max(graph_steps, 1)
    return {
        "normalized_mse": weighted_metrics["normalized_mse"] / divisor,
        "flux_normalized_mse": (
            weighted_metrics["flux_normalized_mse"] / divisor
        ),
        "weighted_total_loss": weighted_metrics["weighted_total_loss"] / divisor,
        "next_state_rmse": float(
            np.sqrt(weighted_metrics["next_state_rmse_squared"] / divisor)
        ),
        "mass_mae": weighted_metrics["mass_mae"] / divisor,
    }


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    *,
    device: torch.device,
    normalization: Normalization,
    target_type: str,
    autoregressive_steps: int,
    mass_projection: bool,
    node_weight_loss: float,
    flux_loss_weight: float,
    flux_normalization: Optional[FluxNormalization],
) -> Dict[str, float]:
    model.eval()
    accumulated = {
        "normalized_mse": 0.0,
        "flux_normalized_mse": 0.0,
        "weighted_total_loss": 0.0,
        "next_state_rmse_squared": 0.0,
        "mass_mae": 0.0,
    }
    graph_steps = 0
    for batch in loader:
        batch = batch.to(device)
        _, metrics = autoregressive_batch(
            model,
            batch,
            normalization=normalization,
            target_type=target_type,
            autoregressive_steps=autoregressive_steps,
            mass_projection=mass_projection,
            node_weight_loss=node_weight_loss,
            flux_loss_weight=flux_loss_weight,
            flux_normalization=flux_normalization,
        )
        weight = int(batch.num_graphs) * autoregressive_steps
        graph_steps += weight
        accumulated["normalized_mse"] += metrics["normalized_mse"] * weight
        accumulated["flux_normalized_mse"] += (
            metrics["flux_normalized_mse"] * weight
        )
        accumulated["weighted_total_loss"] += (
            metrics["weighted_total_loss"] * weight
        )
        accumulated["next_state_rmse_squared"] += (
            metrics["next_state_rmse"] ** 2 * weight
        )
        accumulated["mass_mae"] += metrics["mass_mae"] * weight
    divisor = max(graph_steps, 1)
    return {
        "normalized_mse": accumulated["normalized_mse"] / divisor,
        "flux_normalized_mse": accumulated["flux_normalized_mse"] / divisor,
        "weighted_total_loss": accumulated["weighted_total_loss"] / divisor,
        "next_state_rmse": float(
            np.sqrt(accumulated["next_state_rmse_squared"] / divisor)
        ),
        "mass_mae": accumulated["mass_mae"] / divisor,
    }


def choose_device(requested: str) -> torch.device:
    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    device = torch.device(requested)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA was requested but is not available.")
    if device.type == "mps" and not (
        hasattr(torch.backends, "mps") and torch.backends.mps.is_available()
    ):
        raise RuntimeError("MPS was requested but is not available.")
    return device


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_loader(
    dataset: torch.utils.data.Dataset,
    *,
    batch_size: int,
    shuffle: bool,
    num_workers: int,
    pin_memory: bool,
    generator: Optional[torch.Generator] = None,
) -> DataLoader:
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=num_workers > 0,
        generator=generator,
    )


def format_elapsed_time(seconds: float) -> str:
    total = max(0, int(round(seconds)))
    hours, remainder = divmod(total, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def add_boolean_argument(
    parser: argparse.ArgumentParser, name: str, *, default: bool, help_text: str
) -> None:
    """Add --option/--no-option while retaining JSON-config compatibility."""
    destination = name.replace("-", "_")
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        f"--{name}", dest=destination, action="store_true", help=help_text
    )
    group.add_argument(
        f"--no-{name}", dest=destination, action="store_false"
    )
    parser.set_defaults(**{destination: default})


def build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train a configurable GNN on chemotaxis trajectories."
    )
    parser.add_argument("--config", type=Path, help="Optional JSON configuration.")
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("data/rollout/chemotaxis_varying-Chi.npz"),
    )
    parser.add_argument(
        "--output", type=Path, default=Path("runs/chemotaxis/sageconv")
    )
    parser.add_argument("--model", choices=MODEL_NAMES, default="sageconv")
    parser.add_argument("--target-type", choices=TARGET_TYPES, default="delta")
    parser.add_argument(
        "--autoregressive-steps",
        type=int,
        default=1,
        help="Number of prediction steps unrolled without teacher forcing.",
    )
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--hidden-channels", type=int, default=128)
    parser.add_argument("--num-layers", type=int, default=4)
    parser.add_argument("--dropout", type=float, default=0.1)
    add_boolean_argument(
        parser,
        "layer-norm",
        default=False,
        help_text="Use LayerNorm in learned graph blocks.",
    )
    add_boolean_argument(
        parser,
        "include-chi",
        default=True,
        help_text=(
            "Include trajectory chi as a node feature. Disable this when chi "
            "is fixed across the complete dataset."
        ),
    )
    add_boolean_argument(
        parser,
        "include-drift-velocity",
        default=False,
        help_text=(
            "Include the saved chi*grad(c) x and y components as node "
            "features. Disabled by default for backward compatibility."
        ),
    )
    add_boolean_argument(
        parser,
        "include-absolute-positions",
        default=True,
        help_text=(
            "Include absolute triangle-center x and y coordinates as node "
            "features. Enabled by default for backward compatibility."
        ),
    )
    add_boolean_argument(
        parser,
        "include-boundary-distances",
        default=False,
        help_text=(
            "Include distances from each triangle center to the left, right, "
            "bottom, and top domain boundaries."
        ),
    )
    add_boolean_argument(
        parser,
        "mass-projection",
        default=False,
        help_text=(
            "Project SAGEConv/MeshGraphNet outputs onto exact area-weighted "
            "mass conservation. FluxGraphNet is conservative by construction."
        ),
    )
    add_boolean_argument(
        parser,
        "decode-normalized-flux",
        default=False,
        help_text=(
            "Make FluxGraphNet decode a dimensionless standardized face value, "
            "then transform it to physical transport with training-split flux "
            "mean/std before applying the conservative update."
        ),
    )
    parser.add_argument("--learning-rate", type=float, default=1.0e-3)
    parser.add_argument("--weight-decay", type=float, default=1.0e-5)
    parser.add_argument(
        "--node-weight-loss",
        type=float,
        default=1.0,
        help=(
            "FluxGraphNet-only weight applied to normalized node-state "
            "rollout MSE; ignored for other architectures."
        ),
    )
    parser.add_argument(
        "--flux-loss-weight",
        type=float,
        default=0.0,
        help=(
            "Weight applied to FluxGraphNet's normalized direct interface-flux "
            "MSE; use 0 to disable flux supervision. Ignored for other "
            "architectures."
        ),
    )
    parser.add_argument(
        "--gradient-clip-norm",
        type=float,
        default=1.0,
        help="Clip global gradient norm; use 0 to disable.",
    )
    parser.add_argument("--train-fraction", type=float, default=0.7)
    parser.add_argument("--validation-fraction", type=float, default=0.15)
    parser.add_argument("--test-fraction", type=float, default=0.15)
    parser.add_argument(
        "--patience",
        type=int,
        default=30,
        help="Epochs without validation improvement; use 0 to disable.",
    )
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument(
        "--device", choices=("auto", "cpu", "cuda", "mps"), default="auto"
    )
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument("--log-every", type=int, default=10)
    return parser


def load_config(path: Path, allowed_keys: Sequence[str]) -> Dict[str, object]:
    if not path.is_file():
        raise FileNotFoundError(f"Config file does not exist: {path}")
    with path.open("r", encoding="utf-8") as stream:
        config = json.load(stream)
    if not isinstance(config, dict):
        raise ValueError("The config file must contain one JSON object.")
    unknown = sorted(set(config) - set(allowed_keys))
    if unknown:
        raise ValueError(
            "Unknown config option(s): " + ", ".join(unknown)
        )
    return config


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = build_argument_parser()
    config_parser = argparse.ArgumentParser(add_help=False)
    config_parser.add_argument("--config", type=Path)
    config_args, _ = config_parser.parse_known_args(argv)
    if config_args.config is not None:
        allowed_keys = [
            action.dest
            for action in parser._actions
            if action.dest not in ("help", "config")
        ]
        parser.set_defaults(
            **load_config(config_args.config, allowed_keys)
        )
    args = parser.parse_args(argv)
    args.data = Path(args.data)
    args.output = Path(args.output)
    return args


def resolved_config(args: argparse.Namespace) -> Dict[str, object]:
    result: Dict[str, object] = {}
    for key, value in vars(args).items():
        if key == "config":
            continue
        result[key] = str(value) if isinstance(value, Path) else value
    return result


def validate_args(args: argparse.Namespace, *, max_steps: int) -> None:
    if args.epochs <= 0 or args.batch_size <= 0 or args.hidden_channels <= 0:
        raise ValueError("epochs, batch_size, and hidden_channels must be positive.")
    minimum_layers = 2 if args.model == "sageconv" else 1
    if args.num_layers < minimum_layers:
        raise ValueError(
            f"num_layers must be at least {minimum_layers} for {args.model}."
        )
    if args.autoregressive_steps <= 0 or args.autoregressive_steps > max_steps:
        raise ValueError(
            f"autoregressive_steps must be in [1, {max_steps}]."
        )
    if not (0.0 <= args.dropout < 1.0):
        raise ValueError("dropout must be in [0, 1).")
    if args.learning_rate <= 0.0 or args.weight_decay < 0.0:
        raise ValueError("learning_rate must be positive and weight_decay nonnegative.")
    if args.model == "fluxgraphnet":
        if args.node_weight_loss < 0.0 or args.flux_loss_weight < 0.0:
            raise ValueError(
                "node_weight_loss and flux_loss_weight must be nonnegative."
            )
        if args.node_weight_loss == 0.0 and args.flux_loss_weight == 0.0:
            raise ValueError(
                "At least one of node_weight_loss and flux_loss_weight must "
                "be positive."
            )
    elif args.decode_normalized_flux:
        raise ValueError(
            "decode_normalized_flux is supported only for FluxGraphNet."
        )
    if args.gradient_clip_norm < 0.0:
        raise ValueError("gradient_clip_norm must be nonnegative.")
    if args.patience < 0 or args.num_workers < 0 or args.log_every <= 0:
        raise ValueError("patience/num_workers must be nonnegative; log_every positive.")
    boolean_options = (
        "layer_norm",
        "include_chi",
        "include_drift_velocity",
        "include_absolute_positions",
        "include_boundary_distances",
        "mass_projection",
        "decode_normalized_flux",
    )
    invalid_booleans = [
        name for name in boolean_options if not isinstance(getattr(args, name), bool)
    ]
    if invalid_booleans:
        raise ValueError(
            "These configuration options must be booleans: "
            + ", ".join(invalid_booleans)
        )


def main(argv: Optional[Sequence[str]] = None) -> None:
    args = parse_args(argv)
    data = load_archive(args.data)
    max_steps = int(data["rollout_states"].shape[1] - 1)
    validate_args(args, max_steps=max_steps)
    if args.model == "fluxgraphnet":
        node_weight_loss = float(args.node_weight_loss)
        flux_loss_weight = float(args.flux_loss_weight)
    else:
        # These weights control FluxGraphNet's two-part supervised objective.
        # Other architectures retain their original, unweighted node loss.
        node_weight_loss = 1.0
        flux_loss_weight = 0.0
    set_seed(args.seed)
    device = choose_device(args.device)

    split_ids = split_trajectories(
        int(data["rollout_states"].shape[0]),
        train_fraction=args.train_fraction,
        validation_fraction=args.validation_fraction,
        test_fraction=args.test_fraction,
        seed=args.seed,
    )
    flux_targets = None
    flux_normalization = None
    needs_flux_normalization = (
        flux_loss_weight > 0.0
        or (args.model == "fluxgraphnet" and args.decode_normalized_flux)
    )
    if needs_flux_normalization:
        available_flux_targets = interface_flux_targets(data, args.target_type)
        flux_normalization = compute_flux_normalization(
            available_flux_targets, split_ids["train"]
        )
        if flux_loss_weight > 0.0:
            flux_targets = available_flux_targets
    normalization = compute_normalization(
        data,
        split_ids["train"],
        target_type=args.target_type,
        include_chi=args.include_chi,
        include_drift_velocity=args.include_drift_velocity,
        include_absolute_positions=args.include_absolute_positions,
        include_boundary_distances=args.include_boundary_distances,
    )
    static_node_features, edge_attr, undirected_edge_attr = prepare_features(
        data,
        normalization,
        include_chi=args.include_chi,
        include_drift_velocity=args.include_drift_velocity,
        include_absolute_positions=args.include_absolute_positions,
        include_boundary_distances=args.include_boundary_distances,
    )
    datasets = {
        name: ChemotaxisRolloutDataset(
            data=data,
            trajectory_ids=trajectory_ids,
            autoregressive_steps=args.autoregressive_steps,
            static_node_features=static_node_features,
            edge_attr=edge_attr,
            undirected_edge_attr=undirected_edge_attr,
            flux_targets=flux_targets,
        )
        for name, trajectory_ids in split_ids.items()
    }

    loader_generator = torch.Generator()
    loader_generator.manual_seed(args.seed)
    pin_memory = device.type == "cuda"
    loaders = {
        "train": make_loader(
            datasets["train"],
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
            generator=loader_generator,
        ),
        "validation": make_loader(
            datasets["validation"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
        ),
        "test": make_loader(
            datasets["test"],
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
        ),
    }

    input_channels = 1 + int(static_node_features.shape[-1])
    edge_attr_channels = int(edge_attr.shape[-1])
    model, model_kwargs = build_model(
        args.model,
        in_channels=input_channels,
        edge_attr_channels=edge_attr_channels,
        hidden_channels=args.hidden_channels,
        num_layers=args.num_layers,
        dropout=args.dropout,
        layer_norm=args.layer_norm,
        target_type=args.target_type,
        normalization=normalization,
        decode_normalized_flux=args.decode_normalized_flux,
        flux_normalization=flux_normalization,
    )
    model = model.to(device)
    optimizer = AdamW(
        model.parameters(),
        lr=args.learning_rate,
        weight_decay=args.weight_decay,
    )

    args.output.mkdir(parents=True, exist_ok=True)
    effective_config = resolved_config(args)
    effective_config["node_weight_loss"] = node_weight_loss
    effective_config["flux_loss_weight"] = flux_loss_weight
    config_path = args.output / "config.json"
    checkpoint_path = args.output / "checkpoint.pt"
    history_path = args.output / "history.json"
    with config_path.open("w", encoding="utf-8") as stream:
        json.dump(effective_config, stream, indent=2, sort_keys=True)
        stream.write("\n")

    continuous_feature_names = static_continuous_feature_names(
        include_chi=args.include_chi,
        include_drift_velocity=args.include_drift_velocity,
        include_absolute_positions=args.include_absolute_positions,
        include_boundary_distances=args.include_boundary_distances,
    )
    feature_names = [
        "normalized_density",
        *[f"normalized_{name}" for name in continuous_feature_names],
        "boundary_cell",
    ]
    print(f"device: {device}")
    print(f"model: {args.model} ({type(model).__name__})")
    print(f"target_type: {args.target_type}")
    print(f"autoregressive_steps: {args.autoregressive_steps}")
    print(f"mass_projection: {args.mass_projection}")
    print(f"decode_normalized_flux: {args.decode_normalized_flux}")
    print(f"node_weight_loss: {node_weight_loss}")
    print(f"flux_loss_weight: {flux_loss_weight}")
    if args.model != "fluxgraphnet":
        print(
            "loss-weight config: ignored for this architecture; using the "
            "standard unweighted node objective"
        )
    if flux_normalization is not None:
        print(
            "flux target normalization: "
            f"mean={flux_normalization.mean:.8e}, "
            f"std={flux_normalization.std:.8e}"
        )
    print(
        "trajectories: "
        + ", ".join(f"{name}={ids.size}" for name, ids in split_ids.items())
    )
    print(
        "rollout windows: "
        + ", ".join(f"{name}={len(dataset)}" for name, dataset in datasets.items())
    )
    print(
        f"graph: nodes={data['rollout_states'].shape[2]}, "
        f"directed_edges={data['edge_index'].shape[2]}, "
        f"interior_faces={data['undirected_edge_index'].shape[2]}"
    )
    print("node inputs: " + ", ".join(feature_names))
    print("state-dependent physics-operator inputs: none")

    best_state: Optional[Dict[str, Tensor]] = None
    best_validation = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    history: List[Dict[str, float]] = []

    for epoch in range(1, args.epochs + 1):
        start_time = time.perf_counter()
        train_metrics = train_epoch(
            model,
            loaders["train"],
            optimizer,
            device=device,
            normalization=normalization,
            target_type=args.target_type,
            autoregressive_steps=args.autoregressive_steps,
            mass_projection=args.mass_projection,
            gradient_clip_norm=args.gradient_clip_norm,
            node_weight_loss=node_weight_loss,
            flux_loss_weight=flux_loss_weight,
            flux_normalization=flux_normalization,
        )
        validation_metrics = evaluate(
            model,
            loaders["validation"],
            device=device,
            normalization=normalization,
            target_type=args.target_type,
            autoregressive_steps=args.autoregressive_steps,
            mass_projection=args.mass_projection,
            node_weight_loss=node_weight_loss,
            flux_loss_weight=flux_loss_weight,
            flux_normalization=flux_normalization,
        )
        entry: Dict[str, float] = {"epoch": float(epoch)}
        entry.update({f"train_{key}": value for key, value in train_metrics.items()})
        entry.update(
            {f"validation_{key}": value for key, value in validation_metrics.items()}
        )
        history.append(entry)

        improved = validation_metrics["normalized_mse"] < best_validation
        if improved:
            best_validation = validation_metrics["normalized_mse"]
            best_epoch = epoch
            best_state = copy.deepcopy(model.state_dict())
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if epoch == 1 or epoch % args.log_every == 0 or epoch == args.epochs:
            flux_text = (
                f" | train flux nMSE {train_metrics['flux_normalized_mse']:.6e}"
                f" | val flux nMSE {validation_metrics['flux_normalized_mse']:.6e}"
                if flux_loss_weight > 0.0
                else ""
            )
            print(
                f"epoch {epoch:04d} | "
                f"time {format_elapsed_time(time.perf_counter() - start_time)} | "
                f"train nMSE {train_metrics['normalized_mse']:.6e} | "
                f"val nMSE {validation_metrics['normalized_mse']:.6e} | "
                f"val state RMSE {validation_metrics['next_state_rmse']:.6e} | "
                f"val mass MAE {validation_metrics['mass_mae']:.6e}"
                f"{flux_text}"
            )
        if args.patience > 0 and epochs_without_improvement >= args.patience:
            print(
                f"early stopping at epoch {epoch}; best epoch was {best_epoch}"
            )
            break

    if best_state is None:
        raise RuntimeError("Training did not produce a checkpoint.")
    model.load_state_dict(best_state)
    test_metrics = evaluate(
        model,
        loaders["test"],
        device=device,
        normalization=normalization,
        target_type=args.target_type,
        autoregressive_steps=args.autoregressive_steps,
        mass_projection=args.mass_projection,
        node_weight_loss=node_weight_loss,
        flux_loss_weight=flux_loss_weight,
        flux_normalization=flux_normalization,
    )

    checkpoint = {
        "model_state_dict": {
            key: value.detach().cpu() for key, value in model.state_dict().items()
        },
        "model_class": type(model).__name__,
        "model_name": args.model,
        "model_kwargs": model_kwargs,
        "normalization": asdict(normalization),
        "feature_names": feature_names,
        "feature_options": {
            "include_chi": args.include_chi,
            "include_drift_velocity": args.include_drift_velocity,
            "include_absolute_positions": args.include_absolute_positions,
            "include_boundary_distances": args.include_boundary_distances,
        },
        "edge_attr_columns": str(data.get("edge_attr_columns", "")),
        "target_type": args.target_type,
        "autoregressive_steps": args.autoregressive_steps,
        "mass_projection": args.mass_projection,
        "node_weight_loss": node_weight_loss,
        "flux_loss_weight": flux_loss_weight,
        "flux_normalization": (
            asdict(flux_normalization) if flux_normalization is not None else None
        ),
        "dt": _scalar(data["dt"], "dt"),
        "diffusion": (
            _scalar(data["diffusion"], "diffusion")
            if "diffusion" in data
            else None
        ),
        "data_path": str(args.data),
        "training_args": effective_config,
        "source_config_path": str(args.config) if args.config else None,
        "split_trajectory_ids": {
            name: ids.tolist() for name, ids in split_ids.items()
        },
        "best_epoch": best_epoch,
        "best_validation_normalized_mse": best_validation,
        "test_metrics": test_metrics,
        "history": history,
    }
    torch.save(checkpoint, checkpoint_path)
    with history_path.open("w", encoding="utf-8") as stream:
        json.dump(history, stream, indent=2)
        stream.write("\n")

    print(f"best epoch: {best_epoch}")
    print("test metrics:")
    print(json.dumps(test_metrics, indent=2, sort_keys=True))
    print(f"saved checkpoint: {checkpoint_path}")
    print(f"saved config: {config_path}")
    print(f"saved history: {history_path}")


if __name__ == "__main__":
    main()
